### ISSUE TITLE
Does This Package suppport html like <br>

### ISSUE THREAD

**Issue by talenta-eg** [caffeinated/flash#2]

**Comment by mcordingley** [comment]
Take a look at the view fragment that you include: https://github.com/caffeinated/flash/blob/master/views/message.blade.php

It uses Laravel's normal `{{ }}` template delimiters, which means html entities get escaped. Short answer is then "No."

You can get around this if you implement and include your own version of the view with Laravel's `{!! !!}` delimiters.
