### ISSUE TITLE
No hint path defined for [flash]

### ISSUE THREAD

**Issue by timgavin** [caffeinated/flash#3]
I installed it per the instructions (although Facade is now called Aliases in app.php?) and receive this error:

```
ErrorException in FileViewFinder.php line 112:
No hint path defined for [flash]
```

Using Laravel 5.1.23

**Comment by kaidesu** [comment]
Thanks for the report, I'll take a look into this today~

**Comment by nezaboravi** [comment]
3 years later.... :D :D :D :D
