### ISSUE TITLE
[5.2]Use of Illuminate\Foundation\Application::bindShared causes fatal error.

### ISSUE THREAD

**Issue by ghost** [caffeinated/flash#5]
FatalErrorException in FlashServiceProvider.php line 41:
Call to undefined method Illuminate\Foundation\Application::bindShared()

**Comment by Rahul-sinha** [comment]
First, in the composer.json file need to replace:

"illuminate/html": "^5.0"
with

"laravelcollective/html":"5.4.*"   
Next you need update the composer from the terminal by typing this command in your terminal: composer update.

Next, in the config/app.php file, you replace the:

'Illuminate\Html\HtmlServiceProvider::class'`
with

'Collective\Html\HtmlServiceProvider::class'
Next you replace these two classes aliases:

'Form'      => Illuminate\Html\FormFacade::class,
'Html'      => Illuminate\Html\HtmlFacade::class, 
with

'Form'      => Collective\Html\FormFacade::class,
'Html'      => Collective\Html\HtmlFacade::class,
Lastly, you need to update your routes.php file by replacing the 'web' middleware with:

Route::group(['middleware' => ['web']], function () use ($router) {
    $router->resource('blogs', 'BlogsController');
});
